[package]
name = "zmq-mem"
version = "0.1.0"
authors = ["fecetrulo <felipe@wuzu.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "=0.9.2"